/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_goluck_util_KeyUtil */

#ifndef _Included_top_goluck_util_KeyUtil
#define _Included_top_goluck_util_KeyUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_goluck_util_KeyUtil
 * Method:    getKey
 * Signature: (Ljava/lang/Object;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_top_goluck_util_KeyUtil_getKey
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
