/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_goluck_ndk_2017_1_15_HelloNDKUtil */

#ifndef _Included_top_goluck_ndk_2017_1_15_HelloNDKUtil
#define _Included_top_goluck_ndk_2017_1_15_HelloNDKUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_goluck_ndk_2017_1_15_HelloNDKUtil
 * Method:    getHelloNDK
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_top_goluck_ndk_12017_11_115_HelloNDKUtil_getHelloNDK
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
